# Generated by Django 5.1.2 on 2024-11-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nome',
            field=models.CharField(default='Usuario', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('text', models.CharField(max_length=300)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacao.player')),
            ],
        ),
    ]
